In [1]:
# !pip install pandas numpy matplotlib

In [2]:
# pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.12.0+cpu


In [5]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [7]:
scaler.item()

7

In [8]:
vector = torch.tensor([10,11])

In [9]:
vector

tensor([10, 11])

In [10]:
vector.ndim

1

In [11]:
vector[1].item()

11

In [12]:
vector.shape

torch.Size([2])

In [13]:
matrix = torch.tensor([[8,10],[9,11]])

In [14]:
matrix

tensor([[ 8, 10],
        [ 9, 11]])

In [15]:
matrix.shape

torch.Size([2, 2])

In [16]:
matrix.ndim

2

In [17]:
matrix[0][1]

tensor(10)

In [18]:
#random tensors
# shape : (5,6)
rand_tensor = torch.rand(5, 6)

In [19]:
rand_tensor

tensor([[0.8084, 0.7577, 0.2900, 0.8320, 0.0010, 0.5301],
        [0.6390, 0.6411, 0.2035, 0.0175, 0.7460, 0.6338],
        [0.3626, 0.9094, 0.3420, 0.4636, 0.5375, 0.3373],
        [0.4096, 0.5096, 0.2409, 0.1962, 0.1024, 0.0940],
        [0.3291, 0.3478, 0.9448, 0.1410, 0.9841, 0.8199]])

In [22]:
zeros = torch.zeros(5,6)
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [23]:
zeros*rand_tensor

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [28]:
ones = torch.ones(5,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

In [31]:
rang = torch.arange(0,11,2)
rang

tensor([ 0,  2,  4,  6,  8, 10])

In [35]:
zeros_with_like = torch.zeros_like(input=rang)
zeros_with_like

tensor([0, 0, 0, 0, 0, 0])

In [42]:
tensor = torch.tensor(
    [[1,2,3],[3,6,9]], #the real data
    dtype=None, #by default it's float32
    device='cpu', # when the data stored cpu, cuda ...
    requires_grad=False
)
tensor    

tensor([[1, 2, 3],
        [3, 6, 9]])

In [45]:
%%time
torch.matmul(tensor, tensor.T)

CPU times: user 166 μs, sys: 18 μs, total: 184 μs
Wall time: 163 μs


tensor([[ 14,  42],
        [ 42, 126]])

In [46]:
tensor.T

tensor([[1, 3],
        [2, 6],
        [3, 9]])

In [47]:
tensor.min()

tensor(1)

In [48]:
tensor.max()

tensor(9)

In [61]:
tensor = torch.tensor(data=tensor.data,
                      dtype=torch.float32)

/tmp/ipykernel_21031/45431945.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(data=tensor.data,


In [62]:
tensor.dtype

torch.float32

In [63]:
tensor.mean()

tensor(4.)

In [64]:
tensor.argmin()

tensor(0)

In [65]:
tensor.argmax()

tensor(5)

In [66]:
tensor

tensor([[1., 2., 3.],
        [3., 6., 9.]])